# Generated by Django 4.2.7 on 2023-12-02 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_alter_courses_lab_day_alter_courses_lecture_day_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
