# Generated by Django 4.2.7 on 2023-11-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_alter_courses_course_id_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='user.png', upload_to='images/'),
        ),
    ]
